kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-nfs-sc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: managed-nfs-storage
